### ISSUE TITLE
Should navigation have include_discontinued parameter?

### ISSUE THREAD

**Issue by JohannesFinsveen** [statisticssweden/PxApiSpecs#17]
If so, what to do with empty folders?

**Comment by likp** [comment]
It should be nice if empty folders is not includes in the response although that will require us to traverse the tree to examine if so is the case.

**Comment by JohannesFinsveen** [comment]
traversing the tree is so nice

**Comment by likp** [comment]
Maybe for the future

**Comment by JohannesFinsveen** [comment]
For pxwebapi2
