### ISSUE TITLE
Values on variable

### ISSUE THREAD

**Issue by JohannesFinsveen** [statisticssweden/PxApiSpecs#41]
The text that was here is moved to
https://github.com/statisticssweden/PxApiSpecs/issues/55

**Comment by likp** [comment]
We in our meeting we said that:

Only have one array with all variables. The Order of the variables should be:
    1. Contents
    2. Time
    3. Geographical
    4. Mandatory
    5. The remaining variables
We should also a SortCode property on the variables according to the original order in the data source.
