### ISSUE TITLE
Redo PR 31

### ISSUE THREAD

**Issue by likp** [statisticssweden/PxApiSpecs#55]
PR 31 investigate if values could be on the abstractvariable since the value collection on the ContentsVariabe should be an array of - ContentValue maybe adding a values array of Value on the TimeVariable is the write solution.

**Comment by JohannesFinsveen** [comment]
Currently (after PR 31 ) the
public List<Values> Values
sits on AbstractVariable.

ContentsVariable : AbstractVariable
has public List <ContentValue> Values
this causes
warning CS0108: 'ContentsVariable.Values' hides inherited member 'AbstractVariable.Values'. Use the new keyword if hiding was intended.


An alternative is to move List Values (back) to AbstractCodeListVariable : AbstractVariable and
to TimeVariable : AbstractVariable

Better?

**Comment by likp** [comment]
Yes it think that the later would be the preferred option to go.
